# Generated by Django 3.0.11 on 2024-07-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyblog',
            name='regist_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pyblog',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
